//===================================================================
// COPYRIGHT  2019/12/26
//===================================================================
// CATDialogExt.cpp
// Header definition of class CATDialogExt
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/12/26 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCATDialogExt_H
#define ExportedByCATDialogExt_H
#if defined(__CATDialogExt)
# define ExportedByCATDialogExt   __declspec(dllexport)
#else // __CATDialogExt
# define ExportedByCATDialogExt   __declspec(dllimport)
#endif  // __CATDialogExt
#endif //ExportedByCATDialogExt_H

