//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// ExcelOperator.cpp
// Header definition of class ExcelOperator
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __ExcelOperator
#define ExportedByExcelOperator     __declspec(dllexport)
#else
#define ExportedByExcelOperator     __declspec(dllimport)
#endif
#else
#define ExportedByExcelOperator
#endif
