//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// HTTPRequest.cpp
// Header definition of class HTTPRequest
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __HTTPRequest
#define ExportedByHTTPRequest     __declspec(dllexport)
#else
#define ExportedByHTTPRequest     __declspec(dllimport)
#endif
#else
#define ExportedByHTTPRequest
#endif
