//===================================================================
// COPYRIGHT qws 2022/03/02
//===================================================================
// Base64Code.cpp
// Header definition of class Base64Code
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/02 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef Base64Code_H
#define Base64Code_H

#include "Base64.h"
#include "CATUnicodeString.h"
#include <string>

//-----------------------------------------------------------------------

class ExportedByBase64 Base64Code
{
public:
// Standard constructors and destructors
// -------------------------------------
Base64Code ();
virtual ~Base64Code ();

CATUnicodeString base64_encode(const char *bytes_to_encode,unsigned int in_len);
std::string base64_decode(std::string const &encoded_string);

private:
// Copy constructor and equal operator
// -----------------------------------
Base64Code (Base64Code &);
Base64Code& operator=(Base64Code&);

};

//-----------------------------------------------------------------------

#endif
