//===================================================================
// COPYRIGHT qws 2022/03/02
//===================================================================
// Base64.cpp
// Header definition of class Base64
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/02 Creation: Code generated by the 3DS wizard
//===================================================================

#ifdef  _WINDOWS_SOURCE
#ifdef  __Base64
#define ExportedByBase64     __declspec(dllexport)
#else
#define ExportedByBase64     __declspec(dllimport)
#endif
#else
#define ExportedByBase64
#endif
