// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// HttpConnect.h
// Header definition of HttpConnect
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2019  Creation: Code generated by the CAA wizard  qwsCAA
//===================================================================
#ifndef HttpConnect_H
#define HttpConnect_H

#include "HTTPRequest.h"

#include "CATBaseUnknown.h"
#include <WinSock.h>
#include <sstream>

#include <string>

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href HttpConnect constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new HttpConnect;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByHTTPRequest HttpConnect
{

  public:

  // Standard constructors and destructors
  // -------------------------------------
     HttpConnect ();
     virtual ~HttpConnect ();

	 void socketHttp(std::string host,int port, std::string request);
	 void postData(std::string host,int port, std::string path, std::string post_content);
	 void getData(std::string host, std::string path, std::string get_content);
	 // Copy constructor and equal operator
  // -----------------------------------
  HttpConnect (HttpConnect &);
  HttpConnect& operator=(HttpConnect&);

};

//-----------------------------------------------------------------------

#endif
