//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// JsonMdl
// Header definition of class JsonMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __JsonMdl
#define ExportedByJsonMdl     __declspec(dllexport)
#else
#define ExportedByJsonMdl     __declspec(dllimport)
#endif
#else
#define ExportedByJsonMdl
#endif
