//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// SystemUtility.cpp
// Header definition of class SystemUtility
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef SystemUtility_H
#define SystemUtility_H

#include "SystemMdl.h"
#include "CATBody.h"
#include "CATFace.h"
#include "CATIPrtContainer.h"
#include "CATIProduct.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"

//-----------------------------------------------------------------------

class ExportedBySystemMdl SystemUtility
{
public:
// Standard constructors and destructors
// -------------------------------------
SystemUtility ();
virtual ~SystemUtility ();

/*
	Role    :
		获取网卡的MAC地址
	Param	:	
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date:210406
*/
static CATUnicodeString GetMACID();


/*
	Role    :
		获取别名
	Param	:	
		@ CATBaseUnknown_var : 
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date:210414
*/
static CATUnicodeString GetAlias(CATBaseUnknown_var ispIObj);


/*
	Role    :
		在win_b64目录下搜索文件
	Param	:	
		const CATUnicodeString & iFile : 
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date : 20210601
*/
static CATUnicodeString SearchFile(const CATUnicodeString &iFile);
/*
	Role    :
		删除从起点或重点位置的某个字符（全部）
	Param	:	
		CATUnicodeString iStr : 
		const CATUnicodeChar & iChar : 
		const CATUnicodeString::CATSearchMode & iSearchMode : 
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date : 20210601
*/
static CATUnicodeString StringRemoveChar(CATUnicodeString iStr,const CATUnicodeString &iChar,const CATUnicodeString::CATSearchMode &iSearchMode);
/*
	Role    :
		String to list
	Param	:	
		const CATUnicodeString & isLongString : 
		const CATUnicodeString & isSplitStr : 
	Return	:   
		CATListValCATUnicodeString
	
	Create	:
		liqiang Date : 20210601
*/
static CATListValCATUnicodeString StringToList(const CATUnicodeString& isLongString, const CATUnicodeString& isSplitStr);
/*
	Role    :
		拼接路径和文件，自动处理路径中最后一个字符
	Param	:	
		const CATUnicodeString & iDir : 
		const CATUnicodeString & iFile : 
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date : 20210601
*/
static CATUnicodeString PathAppendFile(const CATUnicodeString &iDir,const CATUnicodeString &iFile);
/*
	Role    :
		显示或不显示
	Param	:	
		CATBaseUnknown_var iObj : 
		bool isHide : 
	Return	:   
		bool
	
	Create	:
		liqiang Date : 20210813
*/
static bool SetVisibility(CATBaseUnknown_var iObj,bool isHide);
/*
	Role    :
		通过产品获取产品路径
	Param	:	
		CATIProduct_var ispIProduct : 
	Return	:   
		CATUnicodeString
	
	Create	:
		liqiang Date : 20220123
*/
static CATUnicodeString GetProductPath(CATIProduct_var ispIProduct);
/*
	Role    :
		通过产品获取产品Doc
	Param	:	
		CATIProduct_var ispIProduct : 
		CATDocument * & oDoc : 
	Return	:   
		HRESULT
	
	Create	:
		liqiang Date : 20220123
*/
static HRESULT GetDocumentFromProduct(CATIProduct_var ispIProduct,CATDocument *&oDoc);
/*
	Role    :
		获取系统用户名
	Param	:	
	Return	:   
		@ CATUnicodeString
	
	Create	:
		liqiang Date : 20220218
*/
static CATUnicodeString GetUserName();
/*
	Role    :
		获取CATIA版本
	Param	:	
	Return	:   
		@ CATUnicodeString
	
	Create	:
		liqiang Date : 20220221
*/
static CATUnicodeString GetCATIAVersion();
/*
	Role    :
		根据日期计算周几
	Param	:	
		@ int y
		@ int m
		@ int d
	Return	:   
		@ int
	
	Create	:
		liqiang Date : 20220221
*/
static int CaculateWeekDay(int y,int m,int d);
/*
	Role    :
		检查路径是否存在
	Param	:	
		@ const CATUnicodeString & iDir
		@ const bool & iCreate
	Return	:   
		@ bool
	
	Create	:
		liqiang Date : 20220317
*/
static bool IsDirectoryExist(const CATUnicodeString &iDir,const bool &iCreate = false);
//************************************
// Method:     Heightlight
// FullName:   SystemUtility::Heightlight
// Access:     public 
// Returns:    HRESULT
// Parameter:  CATBaseUnknown_var iPath
// Description:高亮
//************************************
static HRESULT Heightlight(CATBaseUnknown_var iPath);
//************************************
// Method:     HeightlightFace
// FullName:   SystemUtility::HeightlightFace
// Access:     public static 
// Returns:    HRESULT
// Parameter:  CATFace_var ispFace
// Parameter:  CATBody_var iBody
// Description:高亮face
//************************************
static HRESULT HeightlightFace(CATFace_var ispFace,CATBody_var iBody);
//************************************
// Method:     ClearHeightlight
// FullName:   SystemUtility::ClearHeightlight
// Access:     public 
// Returns:    void
// Description:清楚高亮
//************************************
static void ClearHeightlight();
//************************************
// Method:     ReframeOnHighLight
// FullName:   SystemUtility::ReframeOnHighLight
// Access:     public 
// Returns:    HRESULT
// Description:居中高亮节点
//************************************
static HRESULT ReframeOnHighLight();

//************************************
// Method:     Msg
// FullName:   SystemUtility::Msg
// Access:     public 
// Returns:    int
// Parameter:  CATUnicodeString isMsg
// Parameter:  CATUnicodeString isTitle
// Parameter:  CATDlgStyle Style
// Description:显示阻塞窗口
//************************************
static int Msg(CATUnicodeString isMsg,CATUnicodeString isTitle ,unsigned long Style = (1 << 26));
/*
	Role    :
		获取根节点产品
	Param	:	
		CATIProduct_var & oPrd : 
	Return	:   
		HRESULT
	
	Create	:
		liqiang Date : 20220124
*/
static HRESULT SystemUtility::GetRootProduct(CATIProduct_var &oPrd);

private:
// Copy constructor and equal operator
// -----------------------------------
SystemUtility (SystemUtility &);
SystemUtility& operator=(SystemUtility&);

};

//-----------------------------------------------------------------------

#endif
