//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// SystemMdl.cpp
// Header definition of class SystemMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __SystemMdl
#define ExportedBySystemMdl     __declspec(dllexport)
#else
#define ExportedBySystemMdl     __declspec(dllimport)
#endif
#else
#define ExportedBySystemMdl
#endif
