//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// MD5Sum.cpp
// Header definition of class MD5Sum
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __MD5Sum
#define ExportedByMD5Sum     __declspec(dllexport)
#else
#define ExportedByMD5Sum     __declspec(dllimport)
#endif
#else
#define ExportedByMD5Sum
#endif
