
//===================================================================
// COPYRIGHT  2020/01/06
//===================================================================
// TreeLBNotify.cpp
// Header definition of class TreeLBNotify
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/01/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TreeLBNotify_H
#define TreeLBNotify_H

#include "CATNotification.h"

//-----------------------------------------------------------------------

class TreeLBNotify: public CATNotification

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
TreeLBNotify ();
virtual ~TreeLBNotify ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATNotification
	//------------------------------------


private:
// Copy constructor and equal operator
// -----------------------------------
TreeLBNotify (TreeLBNotify &);
TreeLBNotify& operator=(TreeLBNotify&);
};

//-----------------------------------------------------------------------

#endif

