
//===================================================================
// COPYRIGHT  2020/01/06
//===================================================================
// TreeRBNotify.cpp
// Header definition of class TreeRBNotify
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/01/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TreeRBNotify_H
#define TreeRBNotify_H

#include "CATNotification.h"

//-----------------------------------------------------------------------

class TreeRBNotify: public CATNotification

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
TreeRBNotify ();
virtual ~TreeRBNotify ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATNotification
	//------------------------------------


private:
// Copy constructor and equal operator
// -----------------------------------
TreeRBNotify (TreeRBNotify &);
TreeRBNotify& operator=(TreeRBNotify&);
};

//-----------------------------------------------------------------------

#endif

