// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module GWExportSddData
#======================================================================
#  2019/09/12 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  JS0FM  \
JS0GROUP  \                                                                                                                                                                                                                                                                                                                               
CATDialogEngine \ 
DI0PANV2 \
# END WIZARD EDITION ZONE
