//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// LicMdl
// Header definition of class LicMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __LicMdl
#define ExportedByLicMdl     __declspec(dllexport)
#else
#define ExportedByLicMdl     __declspec(dllimport)
#endif
#else
#define ExportedByLicMdl
#endif
