//===================================================================
// COPYRIGHT devfun 2024/03/19
//===================================================================
// SimpleLicense.cpp
// Header definition of class SimpleLicense
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2024/03/19 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef SimpleLicense_H
#define SimpleLicense_H

#include "LicMdl.h"
#include "CATTime.h"

//-----------------------------------------------------------------------

class ExportedByLicMdl SimpleLicense
{
public:
// Standard constructors and destructors
// -------------------------------------
SimpleLicense ();
virtual ~SimpleLicense ();


bool CheckDateLic(const CATTime &EndTime);
bool Init();
//
// TODO: Add your methods for this class here.
//

private:
// Copy constructor and equal operator
// -----------------------------------
SimpleLicense (SimpleLicense &);
SimpleLicense& operator=(SimpleLicense&);

CATTime StartTime;

};

//-----------------------------------------------------------------------

#endif
