//===================================================================
// COPYRIGHT  2021/04/06
//===================================================================
// DatabaseOperator.cpp
// Header definition of class DatabaseOperator
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __DatabaseOperator
#define ExportedByDatabaseOperator     __declspec(dllexport)
#else
#define ExportedByDatabaseOperator     __declspec(dllimport)
#endif
#else
#define ExportedByDatabaseOperator
#endif
