//===================================================================
// COPYRIGHT devfun 2024/04/01
//===================================================================
// ProductCommonFw.cpp
// Header definition of class ProductCommonFw
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2024/04/01 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByProductCommonFw_H
#define ExportedByProductCommonFw_H
#if defined(__ProductCommonFw)
# define ExportedByProductCommonFw   DSYExport
#else // __ProductCommonFw
# define ExportedByProductCommonFw   DSYImport
#endif  // __ProductCommonFw
#else //ExportedByProductCommonFw_H

#include "DSYExport.h"

#endif //ExportedByProductCommonFw_H

