//===================================================================
// COPYRIGHT  2020/01/06
//===================================================================
// TreeDbNotify.cpp
// Header definition of class TreeDbNotify
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/01/06 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TreeDbNotify.h"

CATImplementClass(TreeDbNotify,Implementation, CATNotification,CATNull);


//-----------------------------------------------------------------------------
// TreeDbNotify : constructor
//-----------------------------------------------------------------------------
TreeDbNotify::TreeDbNotify():CATNotification()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// TreeDbNotify : destructor
//-----------------------------------------------------------------------------
TreeDbNotify::~TreeDbNotify()
{
//
// TODO: Place code here.
//
}



	//------------------------------------
	//	CATNotification
	//------------------------------------






