//===================================================================
// COPYRIGHT  2020/01/06
//===================================================================
// TreeLBNotify.cpp
// Header definition of class TreeLBNotify
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/01/06 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TreeLBNotify.h"

CATImplementClass(TreeLBNotify,Implementation, CATNotification,CATNull);


//-----------------------------------------------------------------------------
// TreeLBNotify : constructor
//-----------------------------------------------------------------------------
TreeLBNotify::TreeLBNotify():CATNotification()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// TreeLBNotify : destructor
//-----------------------------------------------------------------------------
TreeLBNotify::~TreeLBNotify()
{
//
// TODO: Place code here.
//
}



	//------------------------------------
	//	CATNotification
	//------------------------------------






