//===================================================================
// COPYRIGHT  2020/01/06
//===================================================================
// TreeRBNotify.cpp
// Header definition of class TreeRBNotify
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/01/06 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TreeRBNotify.h"

CATImplementClass(TreeRBNotify,Implementation, CATNotification,CATNull);



//-----------------------------------------------------------------------------
// TreeRBNotify : constructor
//-----------------------------------------------------------------------------
TreeRBNotify::TreeRBNotify():CATNotification()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// TreeRBNotify : destructor
//-----------------------------------------------------------------------------
TreeRBNotify::~TreeRBNotify()
{
//
// TODO: Place code here.
//
}



	//------------------------------------
	//	CATNotification
	//------------------------------------






