// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module SystemMdl
#======================================================================
#  2021/04/06 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP	\
JS0FM \
CATObjectModelerBase \
CATVisualization \
CATProductStructure1 \
CATApplicationFrame \
CATInteractiveInterfaces \
DI0PANV2 \
CATMechanicalModeler \




# END WIZARD EDITION ZONE
