//===================================================================
// COPYRIGHT devfun 2024/03/20
//===================================================================
// LicTest.cpp
// Header definition of class LicTest
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2024/03/20 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByLicTest_H
#define ExportedByLicTest_H
#if defined(__LicTest)
# define ExportedByLicTest   DSYExport
#else // __LicTest
# define ExportedByLicTest   DSYImport
#endif  // __LicTest
#else //ExportedByLicTest_H

#include "DSYExport.h"

#endif //ExportedByLicTest_H

